version: 0.2

env:
  variables:
    TF_VAR_remote_state_bucket: "603-terraform-remote-state"
    TF_VAR_remote_state_region: "ap-southeast-2"
    TF_VAR_region: "us-east-1"
    TF_VAR_name: "muzo-fulfillment-handler"
    TF_VAR_build_docker_image: "jch254/docker-node-terraform-aws"
    TF_VAR_build_docker_tag: "6.10.0"
    TF_VAR_github_repository_owner: "jch254"
    TF_VAR_github_repository_name: "muzo-fulfillment-handler"
    TF_VAR_github_branch_name: "master"
    TF_VAR_artifacts_dir: "../dist" # executed from /infrastruture directory
    TF_VAR_runtime: "nodejs6.10"
    TF_VAR_handler: "index.handler"
    TF_VAR_kms_key_arns: '["arn:aws:kms:us-east-1:982898479788:key/0b7b7ba8-721e-4b65-9ff0-21a9e091af76","arn:aws:kms:us-east-1:982898479788:key/e83f1d78-5dc5-4aca-a00b-2fc2ac7bebe4"]'
    TF_VAR_ssm_parameter_arns: '["arn:aws:ssm:us-east-1:982898479788:parameter/muzo-fulfillment-handler/*","arn:aws:ssm:us-east-1:982898479788:parameter/shared/*"]'

phases:
  install:
    commands:
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;
      - ./infrastructure/install.bash

  pre_build:
    commands:
      # Workaround until TF supports creds via Task Roles when running on ECS or CodeBuild
      # See: https://github.com/hashicorp/terraform/issues/8746
      - export AWS_ACCESS_KEY_ID=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.SecretAccessKey'`
      - export AWS_SESSION_TOKEN=`curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.Token'`

      - SPOTIFY_CLIENT_ID=$(aws ssm get-parameters --region $TF_VAR_region --name "/muzo-fulfillment-handler/spotify-client-id" --with-decryption --query Parameters[0].Value)
      - SPOTIFY_CLIENT_SECRET=$(aws ssm get-parameters --region $TF_VAR_region --name "/muzo-fulfillment-handler/spotify-client-secret" --with-decryption --query Parameters[0].Value)
      - export TF_VAR_environment_variables="{ SPOTIFY_CLIENT_ID = $SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET = $SPOTIFY_CLIENT_SECRET }"

      - export TF_VAR_github_oauth_token=$(aws ssm get-parameters --region $TF_VAR_region --name "/shared/github-token" --with-decryption --query Parameters[0].Value --output text)

  build:
    commands:
      - ./infrastructure/build-artifacts.bash
      - ./infrastructure/run-tests.bash
      - ./infrastructure/deploy-infrastructure.bash
